package com.kotlinspringboot.dto

// holds data that will be sent by client
// id will be generated by DB therefore optional
data class CourseDto(
    val id: Int?,
    val name: String,
    val category: String
)